version: '3'

services:
  teste-postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "docker"
    ports:
      - "15432:5432"
    volumes:
      - C:\Users\Nayara\docker\volumes\postgresql:/var/lib/postgresql/data

